spring.application.name=code-executor

# AWS S3 Configuration
aws.accessKey=AKIAXONMJJZ6ZJIURSMG
aws.secretKey=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
aws.region=eu-north-1
aws.bucketName=code-executor-kashiling-21

##
# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/code_executor
spring.datasource.username=root
spring.datasource.password=Sushant
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#
#spring.datasource.url=jdbc:mysql://localhost:3306/codearena_db
#spring.datasource.username=root
#spring.datasource.password=root
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.virtual-host=/
spring.rabbitmq.listener.simple.concurrency=3
spring.rabbitmq.listener.simple.max-concurrency=10